//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartAction {
            get {
                return ((int)(this["StartAction"]));
            }
            set {
                this["StartAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenRender {
            get {
                return ((bool)(this["OpenRender"]));
            }
            set {
                this["OpenRender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProgressiveRender {
            get {
                return ((bool)(this["ProgressiveRender"]));
            }
            set {
                this["ProgressiveRender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double BorderWidth {
            get {
                return ((double)(this["BorderWidth"]));
            }
            set {
                this["BorderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double MinimumSize {
            get {
                return ((double)(this["MinimumSize"]));
            }
            set {
                this["MinimumSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImageAppendVariation {
            get {
                return ((bool)(this["ImageAppendVariation"]));
            }
            set {
                this["ImageAppendVariation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImageCrop {
            get {
                return ((bool)(this["ImageCrop"]));
            }
            set {
                this["ImageCrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int JPEGQuality {
            get {
                return ((int)(this["JPEGQuality"]));
            }
            set {
                this["JPEGQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TabWidth {
            get {
                return ((int)(this["TabWidth"]));
            }
            set {
                this["TabWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleDefaultBold {
            get {
                return ((bool)(this["StyleDefaultBold"]));
            }
            set {
                this["StyleDefaultBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleCommentsBold {
            get {
                return ((bool)(this["StyleCommentsBold"]));
            }
            set {
                this["StyleCommentsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleSymbolsBold {
            get {
                return ((bool)(this["StyleSymbolsBold"]));
            }
            set {
                this["StyleSymbolsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleIdentifiersBold {
            get {
                return ((bool)(this["StyleIdentifiersBold"]));
            }
            set {
                this["StyleIdentifiersBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StyleKeywordsBold {
            get {
                return ((bool)(this["StyleKeywordsBold"]));
            }
            set {
                this["StyleKeywordsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StyleBuiltinsBold {
            get {
                return ((bool)(this["StyleBuiltinsBold"]));
            }
            set {
                this["StyleBuiltinsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleStringsBold {
            get {
                return ((bool)(this["StyleStringsBold"]));
            }
            set {
                this["StyleStringsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleNumbersBold {
            get {
                return ((bool)(this["StyleNumbersBold"]));
            }
            set {
                this["StyleNumbersBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleDefaultItalic {
            get {
                return ((bool)(this["StyleDefaultItalic"]));
            }
            set {
                this["StyleDefaultItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleCommentsItalic {
            get {
                return ((bool)(this["StyleCommentsItalic"]));
            }
            set {
                this["StyleCommentsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleSymbolsItalic {
            get {
                return ((bool)(this["StyleSymbolsItalic"]));
            }
            set {
                this["StyleSymbolsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleIdentifiersItalic {
            get {
                return ((bool)(this["StyleIdentifiersItalic"]));
            }
            set {
                this["StyleIdentifiersItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleKeywordsItalic {
            get {
                return ((bool)(this["StyleKeywordsItalic"]));
            }
            set {
                this["StyleKeywordsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleBuiltinsItalic {
            get {
                return ((bool)(this["StyleBuiltinsItalic"]));
            }
            set {
                this["StyleBuiltinsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleStringsItalic {
            get {
                return ((bool)(this["StyleStringsItalic"]));
            }
            set {
                this["StyleStringsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StyleNumbersItalic {
            get {
                return ((bool)(this["StyleNumbersItalic"]));
            }
            set {
                this["StyleNumbersItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000")]
        public string StyleDefaultColor {
            get {
                return ((string)(this["StyleDefaultColor"]));
            }
            set {
                this["StyleDefaultColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#097BF7")]
        public string StyleCommentsColor {
            get {
                return ((string)(this["StyleCommentsColor"]));
            }
            set {
                this["StyleCommentsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#101010")]
        public string StyleSymbolsColor {
            get {
                return ((string)(this["StyleSymbolsColor"]));
            }
            set {
                this["StyleSymbolsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00567F")]
        public string StyleIdentifiersColor {
            get {
                return ((string)(this["StyleIdentifiersColor"]));
            }
            set {
                this["StyleIdentifiersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#56007F")]
        public string StyleKeywordsColor {
            get {
                return ((string)(this["StyleKeywordsColor"]));
            }
            set {
                this["StyleKeywordsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#007F00")]
        public string StyleBuiltinsColor {
            get {
                return ((string)(this["StyleBuiltinsColor"]));
            }
            set {
                this["StyleBuiltinsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFAA3E")]
        public string StyleStringsColor {
            get {
                return ((string)(this["StyleStringsColor"]));
            }
            set {
                this["StyleStringsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7F7F00")]
        public string StyleNumbersColor {
            get {
                return ((string)(this["StyleNumbersColor"]));
            }
            set {
                this["StyleNumbersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 12pt")]
        public global::System.Drawing.Font EditorFont {
            get {
                return ((global::System.Drawing.Font)(this["EditorFont"]));
            }
            set {
                this["EditorFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("562")]
        public int DocumentSplitter {
            get {
                return ((int)(this["DocumentSplitter"]));
            }
            set {
                this["DocumentSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("677")]
        public int EditorSplitter {
            get {
                return ((int)(this["EditorSplitter"]));
            }
            set {
                this["EditorSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1688, 1005")]
        public global::System.Drawing.Size FormSize {
            get {
                return ((global::System.Drawing.Size)(this["FormSize"]));
            }
            set {
                this["FormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuppressDisplay {
            get {
                return ((bool)(this["SuppressDisplay"]));
            }
            set {
                this["SuppressDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AnimateZoom {
            get {
                return ((bool)(this["AnimateZoom"]));
            }
            set {
                this["AnimateZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RenderWidth {
            get {
                return ((int)(this["RenderWidth"]));
            }
            set {
                this["RenderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RenderHeight {
            get {
                return ((int)(this["RenderHeight"]));
            }
            set {
                this["RenderHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int AnimateWidth {
            get {
                return ((int)(this["AnimateWidth"]));
            }
            set {
                this["AnimateWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int AnimateHeight {
            get {
                return ((int)(this["AnimateHeight"]));
            }
            set {
                this["AnimateHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AnimateLength {
            get {
                return ((int)(this["AnimateLength"]));
            }
            set {
                this["AnimateLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AnimateFrameRate {
            get {
                return ((int)(this["AnimateFrameRate"]));
            }
            set {
                this["AnimateFrameRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnimateCodec {
            get {
                return ((int)(this["AnimateCodec"]));
            }
            set {
                this["AnimateCodec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AnimatePreview {
            get {
                return ((bool)(this["AnimatePreview"]));
            }
            set {
                this["AnimatePreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AnimatePreviewLoop {
            get {
                return ((bool)(this["AnimatePreviewLoop"]));
            }
            set {
                this["AnimatePreviewLoop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GalleryUsername {
            get {
                return ((string)(this["GalleryUsername"]));
            }
            set {
                this["GalleryUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GalleryPassword {
            get {
                return ((string)(this["GalleryPassword"]));
            }
            set {
                this["GalleryPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MultiplyWidth {
            get {
                return ((int)(this["MultiplyWidth"]));
            }
            set {
                this["MultiplyWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MultiplyHeight {
            get {
                return ((int)(this["MultiplyHeight"]));
            }
            set {
                this["MultiplyHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ccLicense {
            get {
                return ((string)(this["ccLicense"]));
            }
            set {
                this["ccLicense"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ccImage {
            get {
                return ((string)(this["ccImage"]));
            }
            set {
                this["ccImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ccName {
            get {
                return ((string)(this["ccName"]));
            }
            set {
                this["ccName"] = value;
            }
        }
    }
}
