#line 2 "lex.yy.cpp"

#line 4 "lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer CfdgFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstring>
/* end standard C++ headers. */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *Cfdgalloc (yy_size_t  );
void *Cfdgrealloc (void *,yy_size_t  );
void Cfdgfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[289] =
    {   0,
        0,    0,   88,   86,   84,   85,   72,   86,    1,   86,
       86,   86,   86,   86,   82,   63,   13,   66,   78,   78,
       78,   78,   78,   86,   78,   37,   35,   78,   78,   29,
       31,   78,   78,   61,   27,   50,   78,   78,   44,   45,
       48,   86,   78,   78,   84,    0,    3,   73,    0,   76,
       19,   79,    2,    1,   82,   79,   82,    0,   64,   70,
       69,   67,    0,    0,   78,   78,   78,   78,   78,   78,
       78,   75,   78,   78,   78,   78,   78,   78,   78,   78,
       15,   78,   78,   78,   78,   78,   78,   46,   47,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   38,   40,

       39,   41,   59,   57,   53,    0,   74,   21,   78,   78,
       78,   22,   79,    0,    0,   79,   81,   79,    0,    0,
       80,    0,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   30,   78,   78,   78,   78,   78,
       78,   78,   33,   78,   78,   78,   78,   78,   78,   78,
       78,   78,    0,    0,    0,    0,   20,   23,   71,   65,
       68,    0,   80,    0,   80,   80,    0,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   18,   16,   78,   28,
       78,   78,   12,   78,   10,   78,    9,   78,   78,   49,
       51,   78,   78,    8,   24,   78,   78,    0,    0,   52,

       55,   80,   80,    0,   78,   77,   78,   78,   78,   78,
       78,   78,   36,   78,   78,   78,   78,   78,   60,   78,
       78,   11,   78,   78,   78,   43,   62,    0,    0,    0,
       83,   78,   78,   78,   78,   78,   78,   78,   78,    7,
       78,   26,   78,   78,   17,   78,   78,   58,    0,    0,
       78,   78,   78,   78,   14,    6,   78,   78,   78,   78,
        0,    0,   78,   78,   78,   78,   78,   78,   78,    0,
        0,   78,   78,   78,   78,   25,   42,    0,    0,    5,
       34,   32,    4,    0,    0,   56,   54,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       14,   14,   14,   14,   14,   14,   14,   17,    1,   18,
       19,   20,    1,    1,   21,   22,   23,   22,   24,   22,
       22,   22,   25,   22,   22,   26,   27,   28,   29,   30,
       22,   31,   32,   33,   34,   35,   22,   22,   36,   22,
        1,    1,    1,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   22,   48,   49,   50,   51,
       52,   53,   22,   54,   55,   56,   57,   22,   58,   59,
       60,   61,    1,   62,    1,    1,    1,   63,   22,   22,
       22,   22,   22,   22,   22,   64,   65,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   66,   22,   67,
       22,   22,   22,   68,   69,   70,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   71,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   72,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   73,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    1,    3,    3,    3,    4,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[293] =
    {   0,
        0,    0,  322, 1158,  318, 1158, 1158,   71, 1158,  303,
      297,  293,   63,   71,   74,   63,  274,  273,   80,   82,
       84,   91,   95,  253,    0,  102,  109,  111,  118,  121,
      125,  128,  132,  135,  142,  149,  164,  145,  174,  197,
      204,  125,  208,  211,  278,   82, 1158, 1158,  262, 1158,
     1158,  217, 1158, 1158,  257,  222,  228,  239, 1158, 1158,
     1158, 1158,  256,   93,  245,    0,  247,  255,  266,  270,
      274, 1158,  277,  284,  288,  291,  295,  302,  304,  306,
      315,  317,  325,  327,  343,  345,  347,  356,  360,  363,
      370,  372,  374,  381,  383,  391,  393,  395,  404,  411,

      414,  427,  214,  207,  194,  209, 1158,  431,  434,  441,
      443, 1158, 1158,  451,  235, 1158, 1158,  456,  463,  420,
      468,   97,  475,  477,  479,  504,  506,  486,  508,  522,
      525,  529,  532,  536,  540,  543,  547,  558,  562,  566,
      569,  573,  576,  586,  588,  598,  606,  602,  609,  618,
      625,  629,  192,  192,  187,  171,  632,  636,  651,  653,
      655,  486,  664,  547,  667, 1158,  113,  675,  677,  679,
      690,  693,  700,  704,  708,  711,  718,  725,  727,  729,
      737,  739,  747,  749,  751,  758,  760,  762,  769,  771,
      773,  781,  783,  790,  792,  794,  806,  180,  172, 1158,

      153, 1158, 1158,  161,  808,  810,  818,  827,  829,  839,
      850,  852,  854,  861,  865,  868,  872,  876,  879,  883,
      886,  890,  893,  897,  912,  919,  921,  165,  157,  146,
      186,  923,  930,  933,  944,  947,  954,  957,  964,  966,
      968,  975,  977,  979,  986,  988,  990, 1158,  137,  144,
     1002, 1004, 1006, 1023, 1020, 1027, 1034, 1036, 1038, 1045,
      126,  113, 1047, 1056, 1059, 1067, 1074, 1077, 1081,  115,
       84, 1084, 1091, 1093, 1100, 1104, 1111,   72,   63, 1113,
     1121, 1123, 1125,   49,   49, 1158, 1158, 1158, 1146, 1149,
     1151, 1154

    } ;

static yyconst flex_int16_t yy_def[293] =
    {   0,
      288,    1,  288,  288,  288,  288,  288,  289,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  290,  290,
      290,  290,  290,  288,  291,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  288,  290,  290,  288,  289,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  292,  292,  290,  291,  290,  290,  290,  290,
      290,  288,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  288,  288,  288,  288,  288,  290,  290,  290,
      290,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  292,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  288,  288,  288,  288,  290,  290,  290,  290,
      290,  288,  288,  288,  288,  288,  292,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  288,  288,  288,

      288,  288,  288,  292,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  288,  288,  288,
      292,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  288,  288,  288,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      288,  288,  290,  290,  290,  290,  290,  290,  290,  288,
      288,  290,  290,  290,  290,  290,  290,  288,  288,  290,
      290,  290,  290,  288,  288,  288,  288,    0,  288,  288,
      288,  288

    } ;

static yyconst flex_int16_t yy_nxt[1232] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,    4,   11,
       12,   13,   14,   15,   15,   15,    4,   16,   17,   18,
       19,   20,   21,   20,   20,   22,   23,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   24,   25,   26,   27,
       28,   20,   29,   30,   20,   31,   32,   20,   33,   20,
       20,   20,   34,   35,   36,   37,   20,   38,   39,   40,
       41,   42,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   43,   44,   47,   51,   47,   52,   52,   52,   53,
       55,   59,   60,   54,   47,   56,   47,   57,   57,   57,
       63,   64,   63,   64,   63,   64,   66,   58,   66,  287,

       66,   63,   64,  286,   64,   63,   64,   66,   64,   68,
       67,   66,   63,   64,  285,   70,   58,   69,   66,   63,
       64,   63,   64,   71,   64,   66,  284,   66,   63,   64,
      279,   63,   64,  122,   66,   63,   64,   66,   63,   64,
      167,   66,   63,   64,   66,   63,   64,   74,   66,   76,
       73,   66,   63,   64,  204,   63,   64,  278,   66,   63,
       64,   66,   75,  103,  104,   66,   77,   78,  271,   79,
      105,   81,   64,   85,   63,   64,  270,   82,   83,  106,
       66,   80,  262,   84,   63,   64,  107,   90,   99,  100,
       66,   98,  261,   86,   91,   92,   93,   64,   87,  250,

       88,   89,  249,  248,   94,  231,   95,   63,   64,  230,
       96,  101,  102,   66,   63,   64,  229,   97,   63,   64,
       66,   63,   64,  113,   66,  228,  201,   66,  116,  200,
       52,   52,   52,  117,   55,  118,  118,  118,  199,   56,
      114,   57,   57,   57,  198,  119,  117,  156,  120,  120,
      155,   58,  121,  121,  121,   63,   64,   63,   64,  114,
      154,   66,  153,   66,  119,   63,   64,   64,  115,  123,
       58,   66,  112,  109,  110,  111,   63,   64,  108,   45,
       63,   64,   66,  124,   63,   64,   66,   63,   64,   72,
       66,   62,   61,   66,   63,   64,  125,  126,   63,   64,

       66,   63,   64,   50,   66,   63,   64,   66,  127,   49,
       48,   66,   63,   64,   63,   64,   63,   64,   66,   45,
       66,  288,   66,  288,  129,   63,   64,   63,   64,  128,
      288,   66,  288,   66,  130,   63,   64,   63,   64,  288,
      288,   66,  288,   66,  288,  131,  288,  288,  135,  132,
      134,  288,  133,   63,   64,   63,   64,   63,   64,   66,
      288,   66,  288,   66,  288,  137,   63,   64,  288,  136,
       63,   64,   66,   63,   64,  288,   66,  288,  138,   66,
       63,   64,   63,   64,   63,   64,   66,  288,   66,  288,
       66,   63,   64,   63,   64,  142,  139,   66,  140,   66,

      141,   63,   64,   63,   64,   63,   64,   66,  144,   66,
      288,   66,  288,  288,   63,   64,  146,  288,  143,  147,
       66,   63,   64,  288,   63,   64,  288,   66,  288,  148,
       66,  151,  145,  121,  121,  121,  152,   63,   64,  149,
      150,   63,   64,   66,   63,   64,  288,   66,  288,  288,
       66,   63,   64,   63,   64,  288,  288,   66,  288,   66,
      162,  162,  116,  288,  163,  163,  163,  288,  288,  118,
      118,  118,  164,  164,  166,  288,  165,  165,  165,  119,
      288,  121,  121,  121,  288,   63,   64,   63,   64,   63,
       64,   66,  288,   66,  288,   66,   63,   64,  119,  163,

      163,  163,   66,  157,  288,  168,  158,  169,  170,  159,
      160,  161,  288,  171,   63,   64,   63,   64,   63,   64,
       66,  288,   66,  288,   66,  288,  288,  172,  288,  173,
      288,  174,   63,   64,  288,   63,   64,  288,   66,   63,
       64,   66,   63,   64,  288,   66,   63,   64,   66,  288,
       63,   64,   66,   63,   64,  175,   66,   63,   64,   66,
      165,  165,  165,   66,  288,  288,  176,  177,   63,   64,
      179,  178,   63,   64,   66,  288,   63,   64,   66,   63,
       64,  288,   66,   63,   64,   66,   63,   64,  180,   66,
      288,  288,   66,  288,  181,  182,   63,   64,   63,   64,

      184,  288,   66,  288,   66,  288,  288,  186,   63,   64,
      183,  185,   63,   64,   66,  187,   63,   64,   66,   63,
       64,  288,   66,  288,  288,   66,  288,  288,   63,   64,
      190,  288,  188,  288,   66,   63,   64,  288,  189,   63,
       64,   66,   63,   64,  288,   66,   63,   64,   66,  288,
      288,  194,   66,  288,  288,  191,  288,  193,  288,  192,
      195,   63,   64,   63,   64,   63,   64,   66,  288,   66,
      202,   66,  288,  203,  288,  196,  288,  163,  163,  163,
      165,  165,  165,  288,  197,   63,   64,   63,   64,   63,
       64,   66,  288,   66,  288,   66,  288,  288,  205,  288,

       63,   64,  207,   63,   64,  206,   66,  288,  288,   66,
       63,   64,  288,  208,   63,   64,   66,  288,   63,   64,
       66,   63,   64,  209,   66,  210,  288,   66,   63,   64,
      211,  288,  212,  288,   66,   63,   64,   63,   64,   63,
       64,   66,  213,   66,  288,   66,  288,   63,   64,   63,
       64,  288,  214,   66,  288,   66,  215,   63,   64,   63,
       64,   63,   64,   66,  288,   66,  288,   66,   63,   64,
       63,   64,   63,   64,   66,  216,   66,  288,   66,   63,
       64,   63,   64,   63,   64,   66,  288,   66,  288,   66,
      217,   63,   64,   63,   64,  218,  288,   66,  219,   66,

       63,   64,   63,   64,   63,   64,   66,  288,   66,  288,
       66,  222,  288,  220,  288,  221,   63,   64,   63,   64,
       63,   64,   66,  224,   66,  288,   66,  288,   63,   64,
      288,  288,  288,  206,   66,  288,  223,   63,   64,   63,
       64,  288,  288,   66,  288,   66,  225,  232,  226,   63,
       64,  227,  235,  288,  288,   66,  288,  233,  288,  234,
       63,   64,   63,   64,   63,   64,   66,  206,   66,  288,
       66,   63,   64,  236,  288,   63,   64,   66,   63,   64,
      206,   66,   63,   64,   66,  288,   63,   64,   66,   63,
       64,  288,   66,   63,   64,   66,   63,   64,  288,   66,

       63,   64,   66,   63,   64,  288,   66,   63,   64,   66,
      288,  288,  288,   66,  237,  288,  239,  241,  288,  288,
      238,  288,   63,   64,  243,  242,  288,  240,   66,   63,
       64,   63,   64,   63,   64,   66,  288,   66,  288,   66,
       63,   64,  245,   63,   64,  288,   66,  244,  288,   66,
      288,  251,  246,  252,   63,   64,  288,   63,   64,  288,
       66,  206,  247,   66,   63,   64,  288,   63,   64,  206,
       66,  288,  206,   66,   63,   64,   63,   64,   63,   64,
       66,  288,   66,  288,   66,   63,   64,   63,   64,   63,
       64,   66,  288,   66,  288,   66,   63,   64,   63,   64,

       63,   64,   66,  288,   66,  253,   66,  254,  288,  288,
      256,  288,   63,   64,   63,   64,   63,   64,   66,  288,
       66,  288,   66,  255,  258,  288,  259,  263,  288,  206,
       63,   64,  257,   63,   64,  288,   66,   63,   64,   66,
      288,  260,  288,   66,   63,   64,   63,   64,   63,   64,
       66,  288,   66,  288,   66,   63,   64,   63,   64,  288,
      288,   66,  264,   66,  288,  265,   63,   64,  288,   63,
       64,  288,   66,  288,  267,   66,  288,   63,   64,  288,
      266,  288,  206,   66,   63,   64,  268,   63,   64,  288,
       66,   63,   64,   66,   63,   64,  288,   66,  269,  288,

       66,   63,   64,   63,   64,  288,  272,   66,  288,   66,
       63,   64,  288,  273,   63,   64,   66,  288,  274,  276,
       66,   63,   64,   63,   64,  280,  275,   66,  288,   66,
      277,   63,   64,   63,   64,   63,   64,   66,  288,   66,
      288,   66,  283,  282,  288,  281,   46,   46,   46,   46,
       65,   65,   65,   66,   66,   63,   63,    3,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288
    } ;

static yyconst flex_int16_t yy_chk[1232] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,   13,    8,   13,   13,   13,   14,
       15,   16,   16,   14,   46,   15,   46,   15,   15,   15,
       19,   19,   20,   20,   21,   21,   19,   15,   20,  285,

       21,   22,   22,  284,   64,   23,   23,   22,  122,   21,
       19,   23,   26,   26,  279,   22,   15,   21,   26,   27,
       27,   28,   28,   23,  167,   27,  278,   28,   29,   29,
      271,   30,   30,   64,   29,   31,   31,   30,   32,   32,
      122,   31,   33,   33,   32,   34,   34,   27,   33,   28,
       26,   34,   35,   35,  167,   38,   38,  270,   35,   36,
       36,   38,   27,   42,   42,   36,   29,   30,  262,   30,
       42,   32,  204,   34,   37,   37,  261,   32,   32,   42,
       37,   31,  250,   33,   39,   39,   42,   36,   39,   39,
       39,   38,  249,   35,   36,   36,   36,  231,   35,  230,

       35,   35,  229,  228,   36,  204,   36,   40,   40,  201,
       37,   40,   40,   40,   41,   41,  199,   37,   43,   43,
       41,   44,   44,   52,   43,  198,  156,   44,   56,  155,
       52,   52,   52,   56,   57,   56,   56,   56,  154,   57,
       52,   57,   57,   57,  153,   56,  115,  106,   58,   58,
      105,   57,   58,   58,   58,   65,   65,   67,   67,   52,
      104,   65,  103,   67,   56,   68,   68,   63,   55,   67,
       57,   68,   49,   44,   44,   44,   69,   69,   43,   45,
       70,   70,   69,   68,   71,   71,   70,   73,   73,   24,
       71,   18,   17,   73,   74,   74,   69,   70,   75,   75,

       74,   76,   76,   12,   75,   77,   77,   76,   71,   11,
       10,   77,   78,   78,   79,   79,   80,   80,   78,    5,
       79,    3,   80,    0,   74,   81,   81,   82,   82,   73,
        0,   81,    0,   82,   75,   83,   83,   84,   84,    0,
        0,   83,    0,   84,    0,   76,    0,    0,   80,   77,
       79,    0,   78,   85,   85,   86,   86,   87,   87,   85,
        0,   86,    0,   87,    0,   83,   88,   88,    0,   82,
       89,   89,   88,   90,   90,    0,   89,    0,   84,   90,
       91,   91,   92,   92,   93,   93,   91,    0,   92,    0,
       93,   94,   94,   95,   95,   87,   85,   94,   85,   95,

       86,   96,   96,   97,   97,   98,   98,   96,   91,   97,
        0,   98,    0,    0,   99,   99,   93,    0,   90,   94,
       99,  100,  100,    0,  101,  101,    0,  100,    0,   95,
      101,   97,   92,  120,  120,  120,   98,  102,  102,   96,
       96,  108,  108,  102,  109,  109,    0,  108,    0,    0,
      109,  110,  110,  111,  111,    0,    0,  110,    0,  111,
      114,  114,  118,    0,  114,  114,  114,    0,    0,  118,
      118,  118,  119,  119,  121,    0,  119,  119,  119,  118,
        0,  121,  121,  121,    0,  123,  123,  124,  124,  125,
      125,  123,    0,  124,    0,  125,  128,  128,  118,  162,

      162,  162,  128,  109,    0,  123,  110,  123,  124,  111,
      111,  111,    0,  125,  126,  126,  127,  127,  129,  129,
      126,    0,  127,    0,  129,    0,    0,  126,    0,  127,
        0,  128,  130,  130,    0,  131,  131,    0,  130,  132,
      132,  131,  133,  133,    0,  132,  134,  134,  133,    0,
      135,  135,  134,  136,  136,  129,  135,  137,  137,  136,
      164,  164,  164,  137,    0,    0,  130,  131,  138,  138,
      133,  132,  139,  139,  138,    0,  140,  140,  139,  141,
      141,    0,  140,  142,  142,  141,  143,  143,  134,  142,
        0,    0,  143,    0,  136,  137,  144,  144,  145,  145,

      139,    0,  144,    0,  145,    0,    0,  141,  146,  146,
      138,  140,  148,  148,  146,  142,  147,  147,  148,  149,
      149,    0,  147,    0,    0,  149,    0,    0,  150,  150,
      145,    0,  143,    0,  150,  151,  151,    0,  144,  152,
      152,  151,  157,  157,    0,  152,  158,  158,  157,    0,
        0,  149,  158,    0,    0,  146,    0,  148,    0,  147,
      150,  159,  159,  160,  160,  161,  161,  159,    0,  160,
      163,  161,    0,  165,    0,  151,    0,  163,  163,  163,
      165,  165,  165,    0,  152,  168,  168,  169,  169,  170,
      170,  168,    0,  169,    0,  170,    0,    0,  168,    0,

      171,  171,  170,  172,  172,  169,  171,    0,    0,  172,
      173,  173,    0,  171,  174,  174,  173,    0,  175,  175,
      174,  176,  176,  172,  175,  172,    0,  176,  177,  177,
      173,    0,  173,    0,  177,  178,  178,  179,  179,  180,
      180,  178,  174,  179,    0,  180,    0,  181,  181,  182,
      182,    0,  175,  181,    0,  182,  176,  183,  183,  184,
      184,  185,  185,  183,    0,  184,    0,  185,  186,  186,
      187,  187,  188,  188,  186,  179,  187,    0,  188,  189,
      189,  190,  190,  191,  191,  189,    0,  190,    0,  191,
      181,  192,  192,  193,  193,  182,    0,  192,  184,  193,

      194,  194,  195,  195,  196,  196,  194,    0,  195,    0,
      196,  189,    0,  186,    0,  188,  197,  197,  205,  205,
      206,  206,  197,  193,  205,    0,  206,    0,  207,  207,
        0,    0,    0,  205,  207,    0,  192,  208,  208,  209,
      209,    0,    0,  208,    0,  209,  195,  207,  196,  210,
      210,  197,  209,    0,    0,  210,    0,  208,    0,  208,
      211,  211,  212,  212,  213,  213,  211,  210,  212,    0,
      213,  214,  214,  211,    0,  215,  215,  214,  216,  216,
      212,  215,  217,  217,  216,    0,  218,  218,  217,  219,
      219,    0,  218,  220,  220,  219,  221,  221,    0,  220,

      222,  222,  221,  223,  223,    0,  222,  224,  224,  223,
        0,    0,    0,  224,  214,    0,  216,  218,    0,    0,
      215,    0,  225,  225,  221,  220,    0,  217,  225,  226,
      226,  227,  227,  232,  232,  226,    0,  227,    0,  232,
      233,  233,  224,  234,  234,    0,  233,  223,    0,  234,
        0,  232,  225,  233,  235,  235,    0,  236,  236,    0,
      235,  234,  226,  236,  237,  237,    0,  238,  238,  235,
      237,    0,  236,  238,  239,  239,  240,  240,  241,  241,
      239,    0,  240,    0,  241,  242,  242,  243,  243,  244,
      244,  242,    0,  243,    0,  244,  245,  245,  246,  246,

      247,  247,  245,    0,  246,  237,  247,  238,    0,    0,
      241,    0,  251,  251,  252,  252,  253,  253,  251,    0,
      252,    0,  253,  239,  244,    0,  246,  251,    0,  252,
      255,  255,  243,  254,  254,    0,  255,  256,  256,  254,
        0,  247,    0,  256,  257,  257,  258,  258,  259,  259,
      257,    0,  258,    0,  259,  260,  260,  263,  263,    0,
        0,  260,  253,  263,    0,  254,  264,  264,    0,  265,
      265,    0,  264,    0,  258,  265,    0,  266,  266,    0,
      257,    0,  263,  266,  267,  267,  259,  268,  268,    0,
      267,  269,  269,  268,  272,  272,    0,  269,  260,    0,

      272,  273,  273,  274,  274,    0,  264,  273,    0,  274,
      275,  275,    0,  265,  276,  276,  275,    0,  266,  268,
      276,  277,  277,  280,  280,  272,  267,  277,    0,  280,
      269,  281,  281,  282,  282,  283,  283,  281,    0,  282,
        0,  283,  275,  274,    0,  273,  289,  289,  289,  289,
      290,  290,  290,  291,  291,  292,  292,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[88] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "../../src-common/cfdg.l"
/* cfdg.l
// this file is part of Context Free
// ---------------------
// Copyright (C) 2005-2008 Mark Lentczner - markl@glyphic.com
// Copyright (C) 2005-2009 John Horigan - john@glyphic.com
// Copyright (C) 2005 Chris Coyne - ccoyne77@gmail.com
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
// 
// John Horigan can be contacted at john@glyphic.com or at
// John Horigan, 1209 Villa St., Mountain View, CA 94041-1123, USA
//
// Mark Lentczner can be contacted at markl@glyphic.com or at
// Mark Lentczner, 1209 Villa St., Mountain View, CA 94041-1123, USA
//
*/
#line 32 "../../src-common/cfdg.l"
    #define YY_NO_UNISTD_H
    #include "builder.h"
    #include "scanner.h"
    #include "astexpression.h"
    #include "cfdg.tab.hpp"

    /* import the parser's token type into a local typedef */
    typedef yy::CfdgParser::token token;
    typedef yy::CfdgParser::token_type token_type;    
    
/* calling this externally    */
/* don't want yywrap to exist.*/
/* The following paragraph suffices to track locations accurately. Each time
 * yylex is invoked, the begin position is moved onto the end position. */
#line 66 "../../src-common/cfdg.l"
#define YY_USER_ACTION  yylloc->columns(yyleng);
#line 844 "lex.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 69 "../../src-common/cfdg.l"


 /* code to place at the beginning of yylex() */

    // reset location
    setupLoc(yylloc);
    
    if (startToken) {
        int t = startToken;
        startToken = 0;
        return t;
    }

                                                                
 /* comment line */
#line 960 "lex.yy.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 289 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 288 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "../../src-common/cfdg.l"
{
                                                                
    int c;
    
    while ((c = yyinput()) != 0) {
        if (c == '\n') break;
    }

    yylloc->lines(1); yylloc->step();
}
	YY_BREAK
/* C-style comment */
case 2:
YY_RULE_SETUP
#line 96 "../../src-common/cfdg.l"
{
    int c;
    bool lastCharWasAStar = false;
 
    // stop when we get to */ or end-of-file
    while ((c = yyinput()) != 0) {
        if (c == '\n') 
            yylloc->lines(1);
        else 
            yylloc->columns();
            
        if (c == '/' && lastCharWasAStar) 
            break;
        
        lastCharWasAStar = c == '*';
    }
    
    if (c == 0) {
        LexerError("end-of-file in C-style comment");
        return token::BADEOF;
    }
    
    yylloc->step();     // move on to next token
}
	YY_BREAK
/* Quoted string */
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 122 "../../src-common/cfdg.l"
{        /* \042 is " in ASCII */
    if (yytext[yyleng - 1] != '\042') {
        LexerError("end-of-line in quoted string");
        return token::BADEOF;
    } else {
        yylval->string = new std::string(yytext + 1, yyleng - 2); 
        return token::USER_QSTRING;
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 132 "../../src-common/cfdg.l"
{return token::STARTSHAPE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 133 "../../src-common/cfdg.l"
{return token::BACKGROUND;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 134 "../../src-common/cfdg.l"
{return token::INCLUDE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 135 "../../src-common/cfdg.l"
{return token::IMPORT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "../../src-common/cfdg.l"
{return token::TILE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "../../src-common/cfdg.l"
{return token::RULE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "../../src-common/cfdg.l"
{return token::PATH;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "../../src-common/cfdg.l"
{return token::SHAPE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 140 "../../src-common/cfdg.l"
{return token::LOOP;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 141 "../../src-common/cfdg.l"
{return token::BECOMES;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 142 "../../src-common/cfdg.l"
{return token::FINALLY;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 143 "../../src-common/cfdg.l"
{return token::IF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "../../src-common/cfdg.l"
{return token::ELSE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "../../src-common/cfdg.l"
{return token::SWITCH;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "../../src-common/cfdg.l"
{return token::CASE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 147 "../../src-common/cfdg.l"
{return token::RANGEOP;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "../../src-common/cfdg.l"
{return token::RANGEOP;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 149 "../../src-common/cfdg.l"
{return token::PLUSMINUSOP;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 150 "../../src-common/cfdg.l"
{return token::PLUSMINUSOP;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 151 "../../src-common/cfdg.l"
{return token::CF_INFINITY;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 153 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::time;          return token::MODTYPE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 154 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::timescale;     return token::MODTYPE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 155 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::rot;           return token::MODTYPE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 156 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::rot;           return token::MODTYPE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 157 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::flip;          return token::MODTYPE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 158 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::flip;          return token::MODTYPE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 159 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::hue;           return token::MODTYPE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 160 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::hue;           return token::MODTYPE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 161 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::sat;           return token::MODTYPE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 162 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::sat;           return token::MODTYPE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 163 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::bright;        return token::MODTYPE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 164 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::bright;        return token::MODTYPE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 165 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::alpha;         return token::MODTYPE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 166 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::alpha;         return token::MODTYPE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 167 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::x1;            return token::MODTYPE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 168 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::y1;            return token::MODTYPE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 169 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::x2;            return token::MODTYPE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 170 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::y2;            return token::MODTYPE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 171 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::transform;     return token::MODTYPE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 172 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::transform;     return token::MODTYPE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 173 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::x;             return token::MODTYPE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 174 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::y;             return token::MODTYPE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 175 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::xrad;          return token::MODTYPE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 176 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::yrad;          return token::MODTYPE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 177 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::z;             return token::MODTYPE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 178 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::size;          return token::MODTYPE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 179 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::size;          return token::MODTYPE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 180 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::skew;          return token::MODTYPE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 181 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targHue;       return token::MODTYPE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 182 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targHue;       return token::MODTYPE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 183 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targSat;       return token::MODTYPE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 184 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targSat;       return token::MODTYPE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 185 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targBright;    return token::MODTYPE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 186 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targBright;    return token::MODTYPE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 187 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targAlpha;     return token::MODTYPE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 188 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targAlpha;     return token::MODTYPE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 189 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::param;         return token::PARAM;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 190 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::param;         return token::PARAM;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 191 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::stroke;        return token::MODTYPE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 193 "../../src-common/cfdg.l"
{ return token::LT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 194 "../../src-common/cfdg.l"
{ return token::LE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 195 "../../src-common/cfdg.l"
{ return token::LE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 196 "../../src-common/cfdg.l"
{ return token::GT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 197 "../../src-common/cfdg.l"
{ return token::GE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 198 "../../src-common/cfdg.l"
{ return token::GE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 199 "../../src-common/cfdg.l"
{ return token::EQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 200 "../../src-common/cfdg.l"
{ return token::NEQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 201 "../../src-common/cfdg.l"
{ return token::NEQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 202 "../../src-common/cfdg.l"
{ return token::NOT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 203 "../../src-common/cfdg.l"
{ return token::AND; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 204 "../../src-common/cfdg.l"
{ return token::OR; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 205 "../../src-common/cfdg.l"
{ return token::XOR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 206 "../../src-common/cfdg.l"
{ return '_'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 208 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_PATHOP;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 209 "../../src-common/cfdg.l"
{
    // This greedy string regex gobbles up Unicode operators. Find the first one
    // and chop the string there.
    yylval->string = new std::string(yytext);
    size_t pos = std::string::npos;
    token_type tok = token::USER_STRING;
    for (tokenMap::iterator it = utf8chars.begin(), eit = utf8chars.end(); 
         it != eit; ++it)
    {
        size_t spos = yylval->string->find(it->second);
        if (spos != std::string::npos && (spos < pos || pos == std::string::npos)) {
            pos = spos;
            tok = it->first;
        }
    }
    
    if (pos == 0) {
        // Unicode operator found at 1st char, Unread all but the operator and
        // return the token for the operator.
        delete yylval->string;
        yylval->string = 0;
        size_t len = strlen(utf8chars[tok]);
        (yylloc->end) += len - yyleng;
        yyless(len);
        return tok;
    }
    
    if (pos != std::string::npos) {
        // Unicode operator found after 1st char. Unread everything from operator to
        // end of string and truncate string before operator.
        yylval->string->resize(pos);
        (yylloc->end) += pos - yyleng;
        yyless(pos);
    }
    return token::USER_STRING;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 245 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_RATIONAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 246 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_RATIONAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 247 "../../src-common/cfdg.l"
{
    yylval->string = new std::string(yytext, yyleng - 2);
    yyless(yyleng - 2);
    (yylloc->end) += -2;
    return token::USER_RATIONAL;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 253 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_RATIONAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 254 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_FILENAME;}
	YY_BREAK
/* gobble up white-spaces */
case 84:
YY_RULE_SETUP
#line 257 "../../src-common/cfdg.l"
{
    yylloc->step();
}
	YY_BREAK
/* gobble up end-of-lines */
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 262 "../../src-common/cfdg.l"
{
    yylloc->lines(1); yylloc->step();
}
	YY_BREAK
/* pass all other characters up to bison */
case 86:
YY_RULE_SETUP
#line 267 "../../src-common/cfdg.l"
{
    return static_cast<int>(*yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 271 "../../src-common/cfdg.l"
{
    if (!YY_CURRENT_BUFFER)
        yyterminate();
    if (!mLocationStack.empty()) {
        *yylloc = mLocationStack.top();
        mLocationStack.pop();
    }
    yylloc->step();
    return token::GOODEOF;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 282 "../../src-common/cfdg.l"
ECHO;
	YY_BREAK
#line 1590 "lex.yy.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	Cfdgfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	Cfdgfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Cfdgrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) Cfdgrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 289 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 289 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 288);

	return yy_is_jam ? 0 : yy_current_state;
}

    void yyFlexLexer::yyunput( int c, register char* yy_bp)
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream* input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Cfdgalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) Cfdgalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		Cfdgfree((void *) b->yy_ch_buf  );

	Cfdgfree((void *) b  );
}

extern "C" int isatty (int );

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)Cfdgalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)Cfdgrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) Cfdgalloc(new_size  );

		else
			(yy_start_stack) = (int *) Cfdgrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Cfdgalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *Cfdgrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void Cfdgfree (void * ptr )
{
	free( (char *) ptr );	/* see Cfdgrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 282 "../../src-common/cfdg.l"



namespace yy {

Scanner::Scanner(std::istream* in,
		 std::ostream* out)
    : yyFlexLexer(in, out), nextLocAction(normalAction), 
      startToken(token::CFDG2), maybeVersion(0)
{
    utf8chars[token::RANGEOP] = "\xe2\x80\xa6";
    utf8chars[token::PLUSMINUSOP] = "\xc2\xb1";
    utf8chars[token::LE] = "\xe2\x89\xa4";
    utf8chars[token::GE] = "\xe2\x89\xa5";
    utf8chars[token::NEQ] = "\xe2\x89\xa0";
    utf8chars[token::CF_INFINITY] = "\xe2\x88\x9e";
}

Scanner::~Scanner()
{
}

void Scanner::set_debug(bool b)
{
    yy_flex_debug = b;
}

void Scanner::LexerError(const char* msg) 
{
    driver->error(lineno(), msg);
}
    
void Scanner::setupLoc(CfdgParser::location_type* yylloc)
{
    switch (nextLocAction) {
        case normalAction:
        case popLoc:
            yylloc->step();
            break;
        case pushLoc:
            mLocationStack.push(*yylloc);
            *yylloc = CfdgParser::location_type();
            break;
    }
    nextLocAction = normalAction;
    yylloc->begin.filename = yylloc->end.filename = driver->m_currentPath;
}
    
}

/* This implementation of CfdgFlexLexer::yylex() is required to fill the
 * vtable of the class CfdgFlexLexer. We define the scanner's main yylex
 * function via YY_DECL to reside in the Scanner class instead. */

#ifdef yylex
#undef yylex
#endif

int yyFlexLexer::yylex()
{
    std::cerr << "in yyFlexLexer::yylex() !" << std::endl;
    return 0;
}


