#line 1 "lex.yy.cpp"

#line 3 "lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 2
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer CfdgFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file; 

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *Cfdgalloc ( yy_size_t  );
void *Cfdgrealloc ( void *, yy_size_t  );
void Cfdgfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[303] =
    {   0,
        0,    0,   90,   88,   86,   87,   87,   74,   88,    1,
       88,   88,   88,   88,   88,   84,   65,   15,   68,   80,
       80,   80,   80,   80,   88,   80,   39,   37,   80,   80,
       31,   33,   80,   80,   57,   29,   46,   80,   80,   42,
       43,   44,   88,   80,   80,   86,   87,    0,    3,    1,
       75,    0,   78,   21,   81,    2,    1,   84,   81,   84,
        0,   66,   72,   71,   69,    0,    0,   80,    0,   80,
       80,   80,   80,   80,   77,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   17,   80,   80,   80,   80,
       80,   80,   80,   63,   64,   80,   80,   80,   80,   80,

       80,   80,   80,   80,   59,   61,   60,   62,   55,   53,
       49,    0,   76,   23,   80,   80,   80,   24,   81,    0,
        1,    0,   81,   83,   81,    0,    0,   82,    0,    0,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   32,   80,   80,   14,   80,   80,   80,
       80,   80,   35,   80,   80,   80,   80,   80,   80,   80,
       80,   80,    0,    0,    0,    0,   22,   25,   73,   67,
       70,    0,   82,    0,   82,   82,    0,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   20,   80,   18,
       80,   30,   80,   80,   12,   80,   10,   80,    9,   80,

       80,   45,   47,   80,   80,    8,   26,   80,   80,    0,
        0,   48,   51,   82,   82,    0,   80,   80,   79,   80,
       80,   80,   80,   80,   80,   38,   80,   80,   13,   80,
       80,   80,   56,   80,   80,   11,   80,   80,   80,   41,
       58,    0,    0,    0,   85,   80,   80,   80,   80,   80,
       80,   80,   80,    7,   80,   28,   80,   80,   19,   80,
       80,   54,    0,    0,   80,   80,   80,   80,   16,    6,
       80,   80,   80,   80,    0,    0,   80,   80,   80,   80,
       80,   80,   80,    0,    0,   80,   80,   80,   80,   27,
       40,    0,    0,    5,   36,   34,    4,    0,    0,   52,

       50,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,    1,    1,
        1,   10,   11,    1,   12,   13,   14,   15,   16,   17,
       15,   15,   15,   15,   15,   15,   15,   18,    1,   19,
       20,   21,    1,    1,   22,   23,   24,   23,   25,   23,
       23,   23,   26,   23,   23,   27,   28,   29,   30,   31,
       23,   32,   33,   34,   35,   36,   23,   23,   37,   23,
        1,    1,    1,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   23,   49,   50,   51,   52,
       53,   54,   23,   55,   56,   57,   58,   23,   59,   60,
       61,   62,    1,   63,    1,    1,    1,   64,   23,   23,
       23,   23,   23,   23,   23,   65,   66,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   67,   23,   68,
       23,   23,   23,   69,   70,   71,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   72,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   73,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   74,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    1,    4,    4,    4,    5,    1,    1,
        1,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6
    } ;

static const flex_int16_t yy_base[311] =
    {   0,
        0,    0,  322, 1229,  316, 1229,  311, 1229,   72,    0,
      304,  295,  286,   64,   72,   75,   64,  276,  274,   81,
       83,   85,   92,   96,  254,  273,  103,  110,  112,  119,
      122,  126,  129,  133,  136,  143,  170,  145,  177,  195,
      218,  155,  158,  179,  210,  280, 1229,  234, 1229,    0,
     1229,  267, 1229, 1229,  233, 1229,    0,  254,  239,  253,
      269, 1229, 1229, 1229, 1229,  250,   94,  247,  244,  275,
      277,  288,  290,  292, 1229,  239,  299,  303,  311,  313,
      320,  322,  324,  331,  338,  334,  342,  345,  349,  352,
      359,  362,  371,  373,  380,  382,  389,  391,  399,  410,

      412,  414,  422,  424,  433,  436,  443,  445,  203,  191,
      187,  199, 1229,  456,  458,  460,  467, 1229, 1229,  471,
        0,  220, 1229, 1229,  476,  483,  227,  488,   98,    0,
      494,  497,  504,  506,  520,  529,  531,  538,  541,  545,
      548,  555,  552,  559,  569,  576,  578,  586,  589,  596,
      598,  600,  607,  615,  618,  629,  636,  633,  640,  643,
      654,  658,  178,  178,  180,  163,  661,  665,  668,  680,
      682,  256,  688,  692,  702, 1229,   74,  198,  708,  710,
      712,  723,  726,  733,  737,  741,  744,  751,  758,  760,
      762,  770,  772,  780,  782,  791,  793,  795,  802,  804,

      806,  813,  816,  823,  827,  831,  835,  842,  845,  168,
      163, 1229,  148, 1229, 1229,  114,  184,  849,  852,  859,
      861,  869,  871,  884,  887,  894,  898,  901,  908,  910,
      912,  919,  921,  923,  930,  932,  934,  953,  943,  960,
      962,  154,  140,  130,  166,  964,  971,  974,  985,  989,
      996, 1005, 1007, 1009, 1016, 1018, 1020, 1027, 1029, 1038,
     1040, 1229,  121,  135, 1049, 1052, 1068, 1070, 1072, 1079,
     1082, 1089, 1086, 1093,  119,  109, 1097, 1100, 1104, 1115,
     1107, 1119, 1126,  120,  111, 1128, 1137, 1144, 1141, 1152,
     1154,   77,   76, 1161, 1163, 1170, 1174,   50,   50, 1229,

     1229, 1229, 1196, 1202, 1206, 1209, 1215, 1219,   83, 1222
    } ;

static const flex_int16_t yy_def[311] =
    {   0,
      302,    1,  302,  302,  302,  302,  302,  302,  303,  304,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  305,
      305,  305,  305,  305,  302,  306,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  302,  305,  305,  302,  302,  303,  302,  304,
      302,  302,  302,  302,  302,  302,  307,  302,  302,  302,
      302,  302,  302,  302,  302,  308,  308,  305,  302,  305,
      305,  305,  305,  305,  302,  306,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  302,  302,
      302,  302,  302,  305,  305,  305,  305,  302,  302,  302,
      307,  302,  302,  302,  302,  302,  302,  302,  308,  309,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  302,  302,  302,  302,  305,  305,  305,  305,
      305,  302,  302,  302,  302,  302,  308,  310,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  302,
      302,  302,  302,  302,  302,  308,  310,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  302,  302,  302,  308,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  302,  302,  302,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  302,  302,  305,  305,  305,  305,
      305,  305,  305,  302,  302,  305,  305,  305,  305,  305,
      305,  302,  302,  305,  305,  305,  305,  302,  302,  302,

      302,    0,  302,  302,  302,  302,  302,  302,  302,  302
    } ;

static const flex_int16_t yy_nxt[1304] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,   11,    4,
       12,   13,   14,   15,   16,   16,   16,    4,   17,   18,
       19,   20,   21,   22,   21,   21,   23,   24,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   25,   26,   27,
       28,   29,   21,   30,   31,   21,   32,   33,   21,   34,
       21,   21,   21,   35,   36,   37,   38,   21,   39,   40,
       41,   42,   43,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   44,   45,   49,   49,   54,   49,   55,   55,
       55,   56,   58,   62,   63,   57,   67,   59,  178,   60,
       60,   60,   66,   67,   66,   67,   66,   67,   69,   61,

       69,  301,   69,   66,   67,  300,   67,   66,   67,   69,
       67,   71,   70,   69,   66,   67,  216,   73,   61,   72,
       69,   66,   67,   66,   67,   74,   67,   69,  299,   69,
       66,   67,  298,   66,   67,  129,   69,   66,   67,   69,
       66,   67,  177,   69,   66,   67,   69,   66,   67,   78,
       69,   80,   77,   69,   66,   67,   66,   67,  293,  245,
       69,   81,   69,  292,   79,  285,   66,   67,   82,   83,
      284,   84,   69,   86,  276,   91,   89,  275,   67,   87,
       88,   66,   67,   85,  264,   90,  263,   69,   66,   67,
       66,   67,  102,  262,   69,   92,   69,  109,  110,  103,

       93,   69,   94,   95,  111,  244,   66,   67,  243,   96,
      105,  106,   69,  112,  242,   69,   97,   98,   99,  213,
      113,   66,   67,  212,  104,  211,  100,   69,  101,   66,
       67,  210,  124,  107,  108,   69,   49,   49,  166,   49,
      119,  128,  128,  128,  165,  164,  123,   55,   55,   55,
      114,  124,  163,  125,  125,  125,   69,  120,   66,   67,
       58,  130,   67,  126,   69,   59,  122,   60,   60,   60,
      173,  173,  173,  115,  116,  117,  120,   61,  118,  127,
      127,   46,  126,  128,  128,  128,   66,   67,   66,   67,
       69,   75,   69,   65,   69,   64,   61,   53,  131,   66,

       67,   66,   67,   66,   67,   69,  132,   69,   52,   69,
       66,   67,   51,   47,   66,   67,   69,   46,  134,  133,
       69,  302,   66,   67,   66,   67,  302,  135,   69,  302,
       69,   66,   67,   66,   67,   66,   67,   69,  302,   69,
      302,   69,   66,   67,  137,   66,   67,  302,   69,   66,
       67,   69,  136,   66,   67,   69,   66,   67,  138,   69,
       66,   67,   69,   66,   67,  302,   69,  302,  139,   69,
       66,   67,  140,   66,   67,  142,   69,  141,  143,   69,
      302,  144,   66,   67,   66,   67,  146,  302,   69,  302,
       69,   66,   67,   66,   67,  145,  302,   69,  302,   69,

       66,   67,   66,   67,  148,  147,   69,  302,   69,  302,
       66,   67,  302,  149,  302,  150,   69,  302,  151,  302,
      152,   66,   67,   66,   67,   66,   67,   69,  154,   69,
      302,   69,  302,   66,   67,   66,   67,  302,  153,   69,
      302,   69,  156,  302,   66,   67,  302,   66,   67,  157,
       69,  302,  155,   69,   66,   67,   66,   67,  302,  158,
       69,  161,   69,  159,  160,  302,  162,   66,   67,   66,
       67,   66,   67,   69,  302,   69,  302,   69,   66,   67,
      302,  172,  172,  123,   69,  173,  173,  173,  302,  302,
      125,  125,  125,  174,  174,  176,  302,  175,  175,  175,

      126,  302,  128,  128,  128,   66,   67,  302,   66,   67,
      302,   69,  302,  302,   69,   66,   67,   66,   67,  126,
      302,   69,  302,   69,  302,  179,  168,  180,  167,  181,
      183,   66,   67,  302,  169,  170,  171,   69,  302,  182,
       66,   67,   66,   67,  184,  302,   69,  302,   69,   66,
       67,  302,   66,   67,  302,   69,   66,   67,   69,   66,
       67,  302,   69,   66,   67,   69,   66,   67,  302,   69,
       66,   67,   69,  302,  302,  185,   69,  302,  302,  186,
       66,   67,  302,  187,  188,  302,   69,   66,   67,   66,
       67,  190,  302,   69,  191,   69,  189,   66,   67,  302,

       66,   67,  302,   69,  302,  192,   69,   66,   67,   66,
       67,   66,   67,   69,  302,   69,  302,   69,   66,   67,
      302,  193,  302,  302,   69,  194,   66,   67,  196,   66,
       67,  302,   69,  302,  302,   69,  302,  198,  302,  195,
       66,   67,  197,  199,   66,   67,   69,   66,   67,  302,
       69,   66,   67,   69,   66,   67,  302,   69,  302,  302,
       69,  202,  302,  302,  200,   66,   67,  302,  201,   66,
       67,   69,   66,   67,  302,   69,   66,   67,   69,   66,
       67,  302,   69,  206,  302,   69,  207,  203,  302,  205,
      204,   66,   67,   66,   67,  214,  302,   69,  302,   69,

      302,  302,  173,  173,  173,  208,  175,  175,  175,  215,
      302,  302,  302,  302,  209,  302,  175,  175,  175,   66,
       67,   66,   67,   66,   67,   69,  302,   69,  302,   69,
      302,  302,  218,  302,   66,   67,  220,   66,   67,  219,
       69,  302,  302,   69,   66,   67,  302,  221,   66,   67,
       69,  302,   66,   67,   69,   66,   67,  222,   69,  223,
      302,   69,   66,   67,  224,  302,  225,  302,   69,   66,
       67,   66,   67,   66,   67,   69,  226,   69,  302,   69,
      302,   66,   67,   66,   67,  302,  227,   69,  302,   69,
      228,   66,   67,   66,   67,  302,  302,   69,  302,   69,

      302,  229,   66,   67,   66,   67,   66,   67,   69,  302,
       69,  230,   69,   66,   67,   66,   67,   66,   67,   69,
      302,   69,  302,   69,   66,   67,  231,   66,   67,  302,
       69,  302,  302,   69,   66,   67,  302,  232,   66,   67,
       69,  233,   66,   67,   69,  302,   66,   67,   69,  236,
      302,  234,   69,   66,   67,  302,   66,   67,  235,   69,
       66,   67,   69,   66,   67,  302,   69,  302,  238,   69,
       66,   67,   66,   67,  302,  219,   69,  302,   69,  237,
       66,   67,   66,   67,  302,  302,   69,  302,   69,  246,
      239,  241,  247,  249,  248,   66,   67,  240,   66,   67,

      219,   69,  302,  302,   69,   66,   67,  302,  250,   66,
       67,   69,   66,   67,  302,   69,  219,  302,   69,   66,
       67,   66,   67,   66,   67,   69,  302,   69,  302,   69,
       66,   67,   66,   67,   66,   67,   69,  302,   69,  302,
       69,   66,   67,   66,   67,   66,   67,   69,  302,   69,
      302,   69,  251,  302,   66,   67,  302,  252,  302,  253,
       69,  255,  302,  302,   66,   67,  256,  302,  254,  257,
       69,   66,   67,   66,   67,   66,   67,   69,  302,   69,
      302,   69,   66,   67,  260,   66,   67,  302,   69,  258,
      302,   69,  302,  265,  302,  266,   66,   67,  302,  259,

       66,   67,   69,  219,  261,  302,   69,   66,   67,  302,
      302,  219,  302,   69,  302,  219,   66,   67,   66,   67,
       66,   67,   69,  302,   69,  302,   69,   66,   67,   66,
       67,   66,   67,   69,  302,   69,  302,   69,   66,   67,
       66,   67,  302,  302,   69,  302,   69,  302,  267,   66,
       67,   66,   67,  302,  302,   69,  268,   69,  302,  270,
       66,   67,  302,   66,   67,  302,   69,  269,  302,   69,
      302,  302,  302,  272,  302,  277,  271,  273,  219,   66,
       67,   66,   67,   66,   67,   69,  302,   69,  302,   69,
       66,   67,  274,   66,   67,  302,   69,   66,   67,   69,

       66,   67,  302,   69,   66,   67,   69,  302,   66,   67,
       69,   66,   67,  279,   69,   66,   67,   69,   66,   67,
      302,   69,  302,  302,   69,  278,   66,   67,  281,  280,
       66,   67,   69,  219,  302,  282,   69,   66,   67,   66,
       67,  302,  302,   69,  302,   69,  302,  283,   66,   67,
      302,  286,   66,   67,   69,   66,   67,  302,   69,  287,
      289,   69,  290,   66,   67,   66,   67,  288,  302,   69,
      294,   69,   66,   67,   66,   67,  291,  302,   69,  302,
       69,   66,   67,  302,  297,   66,   67,   69,  302,  302,
      302,   69,  295,  302,  302,  296,   48,   48,   48,   48,

       48,   48,   50,  302,   50,   50,   50,   50,   68,   68,
       68,   68,   76,   76,   76,  121,  302,  121,  121,  121,
      121,   66,   66,  302,   66,  217,  217,  217,    3,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302
    } ;

static const flex_int16_t yy_chk[1304] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,    9,   14,    9,   14,   14,
       14,   15,   16,   17,   17,   15,  177,   16,  309,   16,
       16,   16,   20,   20,   21,   21,   22,   22,   20,   16,

       21,  299,   22,   23,   23,  298,   67,   24,   24,   23,
      129,   22,   20,   24,   27,   27,  177,   23,   16,   22,
       27,   28,   28,   29,   29,   24,  216,   28,  293,   29,
       30,   30,  292,   31,   31,   67,   30,   32,   32,   31,
       33,   33,  129,   32,   34,   34,   33,   35,   35,   28,
       34,   29,   27,   35,   36,   36,   38,   38,  285,  216,
       36,   29,   38,  284,   28,  276,   42,   42,   30,   31,
      275,   31,   42,   33,  264,   35,   34,  263,  245,   33,
       33,   37,   37,   32,  244,   34,  243,   37,   39,   39,
       44,   44,   38,  242,   39,   36,   44,   43,   43,   38,

       36,  217,   36,   36,   43,  213,   40,   40,  211,   37,
       40,   40,   40,   43,  210,  178,   37,   37,   37,  166,
       43,   45,   45,  165,   39,  164,   37,   45,   37,   41,
       41,  163,  122,   41,   41,   41,   48,   48,  112,   48,
       55,  127,  127,  127,  111,  110,   59,   55,   55,   55,
       44,   59,  109,   59,   59,   59,   76,   55,   68,   68,
       60,   69,   66,   59,   68,   60,   58,   60,   60,   60,
      172,  172,  172,   45,   45,   45,   55,   60,   52,   61,
       61,   46,   59,   61,   61,   61,   70,   70,   71,   71,
       26,   25,   70,   19,   71,   18,   60,   13,   70,   72,

       72,   73,   73,   74,   74,   72,   71,   73,   12,   74,
       77,   77,   11,    7,   78,   78,   77,    5,   73,   72,
       78,    3,   79,   79,   80,   80,    0,   74,   79,    0,
       80,   81,   81,   82,   82,   83,   83,   81,    0,   82,
        0,   83,   84,   84,   78,   86,   86,    0,   84,   85,
       85,   86,   77,   87,   87,   85,   88,   88,   79,   87,
       89,   89,   88,   90,   90,    0,   89,    0,   80,   90,
       91,   91,   81,   92,   92,   83,   91,   82,   84,   92,
        0,   85,   93,   93,   94,   94,   88,    0,   93,    0,
       94,   95,   95,   96,   96,   87,    0,   95,    0,   96,

       97,   97,   98,   98,   90,   89,   97,    0,   98,    0,
       99,   99,    0,   91,    0,   91,   99,    0,   92,    0,
       93,  100,  100,  101,  101,  102,  102,  100,   97,  101,
        0,  102,    0,  103,  103,  104,  104,    0,   96,  103,
        0,  104,   99,    0,  105,  105,    0,  106,  106,  100,
      105,    0,   98,  106,  107,  107,  108,  108,    0,  101,
      107,  103,  108,  102,  102,    0,  104,  114,  114,  115,
      115,  116,  116,  114,    0,  115,    0,  116,  117,  117,
        0,  120,  120,  125,  117,  120,  120,  120,    0,    0,
      125,  125,  125,  126,  126,  128,    0,  126,  126,  126,

      125,    0,  128,  128,  128,  131,  131,    0,  132,  132,
        0,  131,    0,    0,  132,  133,  133,  134,  134,  125,
        0,  133,    0,  134,    0,  131,  116,  131,  115,  132,
      134,  135,  135,    0,  117,  117,  117,  135,    0,  133,
      136,  136,  137,  137,  135,    0,  136,    0,  137,  138,
      138,    0,  139,  139,    0,  138,  140,  140,  139,  141,
      141,    0,  140,  143,  143,  141,  142,  142,    0,  143,
      144,  144,  142,    0,    0,  136,  144,    0,    0,  137,
      145,  145,    0,  138,  139,    0,  145,  146,  146,  147,
      147,  141,    0,  146,  142,  147,  140,  148,  148,    0,

      149,  149,    0,  148,    0,  143,  149,  150,  150,  151,
      151,  152,  152,  150,    0,  151,    0,  152,  153,  153,
        0,  145,    0,    0,  153,  146,  154,  154,  149,  155,
      155,    0,  154,    0,    0,  155,    0,  151,    0,  148,
      156,  156,  150,  152,  158,  158,  156,  157,  157,    0,
      158,  159,  159,  157,  160,  160,    0,  159,    0,    0,
      160,  155,    0,    0,  153,  161,  161,    0,  154,  162,
      162,  161,  167,  167,    0,  162,  168,  168,  167,  169,
      169,    0,  168,  159,    0,  169,  160,  156,    0,  158,
      157,  170,  170,  171,  171,  173,    0,  170,    0,  171,

        0,    0,  173,  173,  173,  161,  174,  174,  174,  175,
        0,    0,    0,    0,  162,    0,  175,  175,  175,  179,
      179,  180,  180,  181,  181,  179,    0,  180,    0,  181,
        0,    0,  179,    0,  182,  182,  181,  183,  183,  180,
      182,    0,    0,  183,  184,  184,    0,  182,  185,  185,
      184,    0,  186,  186,  185,  187,  187,  183,  186,  183,
        0,  187,  188,  188,  184,    0,  184,    0,  188,  189,
      189,  190,  190,  191,  191,  189,  185,  190,    0,  191,
        0,  192,  192,  193,  193,    0,  186,  192,    0,  193,
      187,  194,  194,  195,  195,    0,    0,  194,    0,  195,

        0,  189,  196,  196,  197,  197,  198,  198,  196,    0,
      197,  191,  198,  199,  199,  200,  200,  201,  201,  199,
        0,  200,    0,  201,  202,  202,  193,  203,  203,    0,
      202,    0,    0,  203,  204,  204,    0,  194,  205,  205,
      204,  196,  206,  206,  205,    0,  207,  207,  206,  201,
        0,  198,  207,  208,  208,    0,  209,  209,  200,  208,
      218,  218,  209,  219,  219,    0,  218,    0,  205,  219,
      220,  220,  221,  221,    0,  218,  220,    0,  221,  204,
      222,  222,  223,  223,    0,    0,  222,    0,  223,  220,
      207,  209,  221,  222,  221,  224,  224,  208,  225,  225,

      223,  224,    0,    0,  225,  226,  226,    0,  224,  227,
      227,  226,  228,  228,    0,  227,  225,    0,  228,  229,
      229,  230,  230,  231,  231,  229,    0,  230,    0,  231,
      232,  232,  233,  233,  234,  234,  232,    0,  233,    0,
      234,  235,  235,  236,  236,  237,  237,  235,    0,  236,
        0,  237,  227,    0,  239,  239,    0,  228,    0,  230,
      239,  232,    0,    0,  238,  238,  234,    0,  231,  235,
      238,  240,  240,  241,  241,  246,  246,  240,    0,  241,
        0,  246,  247,  247,  239,  248,  248,    0,  247,  237,
        0,  248,    0,  246,    0,  247,  249,  249,    0,  238,

      250,  250,  249,  248,  240,    0,  250,  251,  251,    0,
        0,  249,    0,  251,    0,  250,  252,  252,  253,  253,
      254,  254,  252,    0,  253,    0,  254,  255,  255,  256,
      256,  257,  257,  255,    0,  256,    0,  257,  258,  258,
      259,  259,    0,    0,  258,    0,  259,    0,  251,  260,
      260,  261,  261,    0,    0,  260,  252,  261,    0,  255,
      265,  265,    0,  266,  266,    0,  265,  253,    0,  266,
        0,    0,    0,  258,    0,  265,  257,  260,  266,  267,
      267,  268,  268,  269,  269,  267,    0,  268,    0,  269,
      270,  270,  261,  271,  271,    0,  270,  273,  273,  271,

      272,  272,    0,  273,  274,  274,  272,    0,  277,  277,
      274,  278,  278,  268,  277,  279,  279,  278,  281,  281,
        0,  279,    0,    0,  281,  267,  280,  280,  272,  271,
      282,  282,  280,  277,    0,  273,  282,  283,  283,  286,
      286,    0,    0,  283,    0,  286,    0,  274,  287,  287,
        0,  278,  289,  289,  287,  288,  288,    0,  289,  279,
      281,  288,  282,  290,  290,  291,  291,  280,    0,  290,
      286,  291,  294,  294,  295,  295,  283,    0,  294,    0,
      295,  296,  296,    0,  289,  297,  297,  296,    0,    0,
        0,  297,  287,    0,    0,  288,  303,  303,  303,  303,

      303,  303,  304,    0,  304,  304,  304,  304,  305,  305,
      305,  305,  306,  306,  306,  307,    0,  307,  307,  307,
      307,  308,  308,    0,  308,  310,  310,  310,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[90] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "../../src-common/cfdg.l"
/* cfdg.l
// this file is part of Context Free
// ---------------------
// Copyright (C) 2005-2008 Mark Lentczner - markl@glyphic.com
// Copyright (C) 2005-2014 John Horigan - john@glyphic.com
// Copyright (C) 2005 Chris Coyne - ccoyne77@gmail.com
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
// 
// John Horigan can be contacted at john@glyphic.com or at
// John Horigan, 1209 Villa St., Mountain View, CA 94041-1123, USA
//
// Mark Lentczner can be contacted at markl@glyphic.com or at
// Mark Lentczner, 1209 Villa St., Mountain View, CA 94041-1123, USA
//
*/
#line 32 "../../src-common/cfdg.l"
    #define YY_NO_UNISTD_H
    #include "builder.h"
    #include "scanner.h"
    #include "astexpression.h"
    #include "cfdg.tab.hpp"

    /* import the parser's token type into a local typedef */
    typedef yy::CfdgParser::token token;
    typedef yy::CfdgParser::token_type token_type;    
    
#line 850 "lex.yy.cpp"
/* calling this externally    */
/* don't want yywrap to exist.*/
/* The following paragraph suffices to track locations accurately. Each time
 * yylex is invoked, the begin position is moved onto the end position. */
#line 68 "../../src-common/cfdg.l"
#define YY_USER_ACTION  yylloc->columns(utf8length(yytext, yyleng));
#line 857 "lex.yy.cpp"
#line 858 "lex.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 71 "../../src-common/cfdg.l"


#line 74 "../../src-common/cfdg.l"
 /* code to place at the beginning of yylex() */

    // reset location
    setupLoc(yylloc);
    
    if (atStartup) {
        int t = startToken;
        atStartup = false;
        return t;
    }

                                                                
 /* comment line */
#line 1007 "lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 303 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 302 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "../../src-common/cfdg.l"
{
    yylloc->step();
}
	YY_BREAK
/* C-style comment */
case 2:
YY_RULE_SETUP
#line 92 "../../src-common/cfdg.l"
{
    int c;
    char lastChar = ' ';
 
    // stop when we get to */ or end-of-file
    while ((c = yyinput()) != YY_NULL) {
        if (c == '\n') {
            // Unix or Windows EOL
            yylloc->lines(1);
        } else if (lastChar == '\r') {
            // Previous character was a Mac OS9 EOL
            yylloc->lines(1);
            yylloc->columns();
        } else {
            yylloc->columns();
        }
        
        if (c == '/' && lastChar == '*')
            break;
        
        lastChar = c;
    }
    
    if (c == YY_NULL) {
        LexerError("end-of-file in block comment");
        return token::BADEOF;
    }
    
    yylloc->step();     // move on to next token
}
	YY_BREAK
/* Quoted string */
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 124 "../../src-common/cfdg.l"
{        /* \042 is " in ASCII */
    if (yytext[yyleng - 1] != '\042') {
        LexerError("end-of-line in quoted string");
        return token::BADEOF;
    } else {
        yylval->string = new std::string(yytext + 1, yyleng - 2); 
        return token::USER_QSTRING;
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 134 "../../src-common/cfdg.l"
{return token::STARTSHAPE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 135 "../../src-common/cfdg.l"
{return token::BACKGROUND;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 136 "../../src-common/cfdg.l"
{return token::INCLUDE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 137 "../../src-common/cfdg.l"
{return token::IMPORT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 138 "../../src-common/cfdg.l"
{return token::TILE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 139 "../../src-common/cfdg.l"
{return token::RULE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 140 "../../src-common/cfdg.l"
{return token::PATH;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 141 "../../src-common/cfdg.l"
{return token::SHAPE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 142 "../../src-common/cfdg.l"
{return token::LOOP;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 143 "../../src-common/cfdg.l"
{return token::CLONE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 144 "../../src-common/cfdg.l"
{return token::LET;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 145 "../../src-common/cfdg.l"
{return token::BECOMES;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 146 "../../src-common/cfdg.l"
{return token::FINALLY;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 147 "../../src-common/cfdg.l"
{return token::IF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 148 "../../src-common/cfdg.l"
{return token::ELSE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 149 "../../src-common/cfdg.l"
{return token::SWITCH;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 150 "../../src-common/cfdg.l"
{return token::CASE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 151 "../../src-common/cfdg.l"
{return token::RANGEOP;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 152 "../../src-common/cfdg.l"
{return token::RANGEOP;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 153 "../../src-common/cfdg.l"
{return token::PLUSMINUSOP;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 154 "../../src-common/cfdg.l"
{return token::PLUSMINUSOP;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 155 "../../src-common/cfdg.l"
{return token::CF_INFINITY;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 157 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::time;          return token::MODTYPE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::timescale;     return token::MODTYPE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 159 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::rot;           return token::MODTYPE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 160 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::rot;           return token::MODTYPE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 161 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::flip;          return token::MODTYPE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 162 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::flip;          return token::MODTYPE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 163 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::hue;           return token::MODTYPE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 164 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::hue;           return token::MODTYPE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 165 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::sat;           return token::MODTYPE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 166 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::sat;           return token::MODTYPE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 167 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::bright;        return token::MODTYPE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 168 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::bright;        return token::MODTYPE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::alpha;         return token::MODTYPE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::alpha;         return token::MODTYPE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 171 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::transform;     return token::MODTYPE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 172 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::transform;     return token::MODTYPE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 173 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::x;             return token::MODTYPE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 174 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::y;             return token::MODTYPE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::z;             return token::MODTYPE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::size;          return token::MODTYPE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 177 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::size;          return token::MODTYPE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 178 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::skew;          return token::MODTYPE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 179 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targHue;       return token::MODTYPE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 180 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targHue;       return token::MODTYPE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 181 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targSat;       return token::MODTYPE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 182 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targSat;       return token::MODTYPE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 183 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targBright;    return token::MODTYPE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 184 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targBright;    return token::MODTYPE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 185 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targAlpha;     return token::MODTYPE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 186 "../../src-common/cfdg.l"
{yylval->modToken = AST::ASTmodTerm::targAlpha;     return token::MODTYPE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 188 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::param); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 189 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::param); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 190 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::stroke); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 191 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::x1); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 192 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::y1); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 193 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::x2); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 194 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::y2); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 195 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::xrad); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 196 "../../src-common/cfdg.l"
{ return v2token(yylval, AST::ASTmodTerm::yrad); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 198 "../../src-common/cfdg.l"
{ return token::LT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 199 "../../src-common/cfdg.l"
{ return token::LE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 200 "../../src-common/cfdg.l"
{ return token::LE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 201 "../../src-common/cfdg.l"
{ return token::GT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 202 "../../src-common/cfdg.l"
{ return token::GE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 203 "../../src-common/cfdg.l"
{ return token::GE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 204 "../../src-common/cfdg.l"
{ return token::EQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 205 "../../src-common/cfdg.l"
{ return token::NEQ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 206 "../../src-common/cfdg.l"
{ return token::NEQ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 207 "../../src-common/cfdg.l"
{ return token::NOT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 208 "../../src-common/cfdg.l"
{ return token::AND; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 209 "../../src-common/cfdg.l"
{ return token::OR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 210 "../../src-common/cfdg.l"
{ return token::XOR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 211 "../../src-common/cfdg.l"
{ return '_'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 213 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_PATHOP;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 214 "../../src-common/cfdg.l"
{
    // This greedy string regex gobbles up Unicode operators. Find the first one
    // and chop the string there.
    yylval->string = new std::string(yytext);
    size_t pos = std::string::npos;
    token_type tok = token::USER_STRING;
    for (tokenMap::value_type& tokenEntry: utf8chars) {
        size_t spos = yylval->string->find(tokenEntry.second);
        if (spos != std::string::npos && (spos < pos || pos == std::string::npos)) {
            pos = spos;
            tok = tokenEntry.first;
        }
    }
    
    if (pos == 0) {
        // Unicode operator found at 1st char, Unread all but the operator and
        // return the token for the operator.
        delete yylval->string;
        yylval->string = nullptr;
        size_t len = strlen(utf8chars[tok]);
        (yylloc->end) = (yylloc->begin);
        yylloc->columns(1);
        yyless(static_cast<int>(len));
        return tok;
    }
    
    if (pos != std::string::npos) {
        // Unicode operator found after 1st char. Unread everything from operator to
        // end of string and truncate string before operator.
        yylval->string->resize(pos);
        (yylloc->end) = (yylloc->begin);
        yylloc->columns(utf8length(yytext, pos));
        yyless(static_cast<int>(pos));
        return token::USER_STRING;
    }
    int c = yyinput();
    if (c != YY_NULL) unput(c);
    return c == '[' ? token::USER_ARRAYNAME : token::USER_STRING;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 253 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_RATIONAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 254 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_RATIONAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 255 "../../src-common/cfdg.l"
{
    yylval->string = new std::string(yytext, yyleng - 2);
    yyless(yyleng - 2);
    (yylloc->end) += -2;
    return token::USER_RATIONAL;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 261 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_RATIONAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 262 "../../src-common/cfdg.l"
{yylval->string = new std::string(yytext); return token::USER_FILENAME;}
	YY_BREAK
/* gobble up white-spaces */
case 86:
YY_RULE_SETUP
#line 265 "../../src-common/cfdg.l"
{
    yylloc->step();
}
	YY_BREAK
/* gobble up end-of-lines */
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 270 "../../src-common/cfdg.l"
{
    yylloc->lines(1); yylloc->step();
}
	YY_BREAK
/* pass all other characters up to bison */
case 88:
YY_RULE_SETUP
#line 275 "../../src-common/cfdg.l"
{
    return static_cast<int>(*yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 279 "../../src-common/cfdg.l"
{
    if (!YY_CURRENT_BUFFER)
        yyterminate();
    if (!mLocationStack.empty()) {
        *yylloc = mLocationStack.top();
        mLocationStack.pop();
    }
    yylloc->step();
    return token::GOODEOF;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 290 "../../src-common/cfdg.l"
ECHO;
	YY_BREAK
#line 1623 "lex.yy.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	Cfdgfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	Cfdgfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Cfdgrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) Cfdgrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 303 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 303 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 302);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Cfdgalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) Cfdgalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		Cfdgfree((void *) b->yy_ch_buf  );

	Cfdgfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = (&file == 0) ? NULL : file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)Cfdgalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)Cfdgrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) Cfdgalloc(new_size  );

		else
			(yy_start_stack) = (int *) Cfdgrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Cfdgalloc (yy_size_t  size )
{
			return malloc(size);
}

void *Cfdgrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void Cfdgfree (void * ptr )
{
			free( (char *) ptr );	/* see Cfdgrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 290 "../../src-common/cfdg.l"


namespace yy {

Scanner::Scanner(std::istream* in, std::ostream* out)
    : yyFlexLexer(in, out), nextLocAction(normalAction), 
      startToken(token::CFDG2), maybeVersion(0), atStartup(true)
{
    utf8chars[token::RANGEOP] = "\xe2\x80\xa6";
    utf8chars[token::PLUSMINUSOP] = "\xc2\xb1";
    utf8chars[token::LE] = "\xe2\x89\xa4";
    utf8chars[token::GE] = "\xe2\x89\xa5";
    utf8chars[token::NEQ] = "\xe2\x89\xa0";
    utf8chars[token::CF_INFINITY] = "\xe2\x88\x9e";
}

Scanner::~Scanner()
{
}

void Scanner::set_debug(bool b)
{
    yy_flex_debug = b;
}

void Scanner::LexerError(const char* msg) 
{
    driver->error(lineno(), msg);
}
    
void Scanner::setupLoc(CfdgParser::location_type* yylloc)
{
    switch (nextLocAction) {
        case normalAction:
        case popLoc:
            yylloc->step();
            break;
        case pushLoc:
            mLocationStack.push(*yylloc);
            *yylloc = CfdgParser::location_type();
            break;
    }
    nextLocAction = normalAction;
    yylloc->begin.filename = yylloc->end.filename = driver->m_currentPath;
}

// Compute the number of Unicode characters in a block of UTF-8 encoded bytes
unsigned int Scanner::utf8length(const char* txt, size_t len)
{
    unsigned int length = 0;
    for (size_t i = 0; i < len; ++i, ++length) {
        unsigned char c = static_cast<unsigned char>(txt[i]);
        if (c == '\0')
            LexerError("Invalid UTF-8 encoding: ASCII null character");
        if ((c & 0x80) == 0) continue;
        size_t j = 0;
        for (; c & 0x80; ++j)
            c <<= 1;
        
        if (j == 1) {
            LexerError("Invalid UTF-8 encoding: unexpected continuation byte");
            continue;
        }
        
        if (j > 4)      // 4 bytes max per RFC 3629
            LexerError("Invalid UTF-8 encoding: code point out of range");
        
        if (j && i + j > len) {
            LexerError("Invalid UTF-8 encoding: sequence extends past end of buffer");
            return length;
        }
        
        // Compute the Unicode code point
        unsigned long code = (c & 0x7f) >> j;
        size_t k = 1;
        for (; k < j; ++k) {
            if ((txt[i + k] & 0xc0) != 0x80) {
                LexerError("Invalid UTF-8 encoding: expecting a continuation byte");
                break;
            }
            code = (code << 6) | (txt[i + k] & 0x3f);
        }
        if (k < j) {
            // malformed code is actually k bytes long, not j bytes long
            i += k - 1;
            continue;
        }
        
        // Check for illegal code points
        if (code >= 0xd800 && code <= 0xdfff)
            LexerError("Invalid UTF-8 encoding: UTF-16 surrogate halves");
        if (code == 0xfffe || code == 0xffff)
            LexerError("Invalid UTF-8 encoding: illegal code point");
        if (code == 0)
            LexerError("Invalid UTF-8 encoding: encoded null character");
        if (code > 0x10ffff)
            LexerError("Invalid UTF-8 encoding: codepoint above U+10FFFF");
        
        // Check for encodings that are more bytes than they need to be
        switch (j) {
            case 2:
                if (code > 0x7f) break;
		[[fallthrough]];
            case 3:
                if (code > 0x7ff) break;
		[[fallthrough]];
            case 4:
                if (code > 0xffff) break;
                LexerError("Invalid UTF-8 encoding: overlong sequence");
            default:
                break;
        }
        if (j)
            i += j - 1;
    }
    return length;
}

CfdgParser::token_type Scanner::v2token(CfdgParser::semantic_type* yylval,
                                        AST::ASTmodTerm::modTypeEnum mod)
{
    if (startToken == token::CFDG2) {
        yylval->modToken = mod;
        return mod == AST::ASTmodTerm::param ? token::PARAM : token::MODTYPE;
    } else {
        yylval->string = new std::string(yytext);
        return token::USER_STRING;
    }
}

}   // namespace yy

/* This implementation of CfdgFlexLexer::yylex() is required to fill the
 * vtable of the class CfdgFlexLexer. We define the scanner's main yylex
 * function via YY_DECL to reside in the Scanner class instead. */

#ifdef yylex
#undef yylex
#endif

int yyFlexLexer::yylex()
{
    std::cerr << "in yyFlexLexer::yylex() !" << std::endl;
    return 0;
}


