//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ContextFree.rc
//
#define IDCANCEL2                       3
#define IDT_LENGTH                      4
#define IDD_CUSTOM_TEMPLATE             5
#define IDR_CFDGTYPE_CNTR_IP            6
#define IDR_APP_PNG                     7
#define IDB_BITMAP_HSB                  8
#define IDB_BITMAP_B                    9
#define IDT_STATUS                      10
#define IDD_CUSTOM_TEMPLATE_98          11
#define IDD_SAVEIMAGE_TEMPLATE          12
#define IDD_SAVEIMAGE_TEMPLATE_98       13
#define IDD_DIALOG_COLORS               28
#define IDS_URL_CFDG                    30
#define IDS_URL_CONTEXTFREE             31
#define IDS_URL_FORUM                   32
#define IDS_URL_FEEDBACK                33
#define IDS_URL_GALLERY                 34
#define IDS_EX_CILIASUN                 40
#define IDS_EX_DEMO1                    41
#define IDS_EX_DEMO2                    42
#define IDS_EX_FUNKY_FLOWER             43
#define IDS_EX_LESSON                   44
#define IDS_EX_LESSON2                  45
#define IDS_EX_MTREE                    46
#define IDS_EX_OCTOPI                   47
#define IDS_EX_POINT                    48
#define IDS_EX_ROSE                     48
#define IDS_EX_QUADCITY                 49
#define IDS_EX_SIERPINSKI               50
#define IDS_EX_SNOWFLAKE                51
#define IDS_EX_TANGLE                   52
#define IDS_EX_TRIPLES                  53
#define IDS_EX_UNDERGROUND              54
#define IDS_EX_WEIGHTING_DEMO           55
#define IDS_EX_WELCOME                  56
#define IDS_EX_ZIGGY                    57
#define IDS_EX_I_CURVES                 58
#define IDS_EX_I_PIX                    59
#define IDS_EX_I_POLYS                  60
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDR_MAINFRAME                   128
#define IDR_CFDGTYPE                    129
#define IDD_CONTROL_BAR                 131
#define IDC_DROPPER                     133
#define IDC_RENDER                      134
#define IDC_MARKER                      135
#define IDC_MOVIE_LENGTH                136
#define IDC_SAVE_IMAGE                  137
#define IDC_LENGTH_UNITS                138
#define IDC_EDIT_WIDTH                  139
#define IDD_RENDER                      140
#define IDD_RENDER_OPTIONS              141
#define IDC_JPEG_QUAL_DEF               142
#define IDD_RENDER_SIZE                 143
#define IDR_RENDER_POPUP                144
#define IDC_EDIT_FRAME                  145
#define IDC_PROGRESS1                   146
#define IDC_STATUS_BAR                  147
#define IDC_IMAGE_APPEND                148
#define IDC_IMAGE_EMBED                 149
#define IDI_BUSY0                       160
#define IDI_BUSY1                       161
#define IDI_BUSY2                       162
#define IDI_BUSY3                       163
#define IDI_BUSY4                       164
#define IDI_BUSY5                       165
#define IDI_BUSY6                       166
#define IDI_BUSY7                       167
#define IDI_BUSY8                       168
#define IDI_BUSY9                       169
#define IDI_BUSY10                      170
#define IDI_BUSY11                      171
#define IDI_BUSY12                      172
#define IDI_BUSY13                      173
#define IDI_BUSY14                      174
#define IDI_BUSY15                      175
#define IDB_COLORWHEEL                  176
#define IDD_RENDER_SVG                  177
#define IDD_RENDER_ANIMATE              178
#define IDD_SAVEIMAGE_TEMPLATE_NT       180
#define IDD_CUSTOM_TEMPLATE_NT          181
#define IDD_UPLOAD                      182
#define IDB_DROPPER                     186
#define IDD_UPLOAD_DESIGN               187
#define IDD_UPLOAD_ACCT                 188
#define IDD_UPLOAD_STATUS               189
#define IDC_COPY_NEW                    200
#define IDC_EDIT_HUE                    201
#define IDC_EDIT_SAT                    202
#define IDC_EDIT_VAL                    203
#define IDC_TEXT_NEW                    204
#define IDC_EDIT_HUE_OLD                205
#define IDC_EDIT_SAT_OLD                206
#define IDC_EDIT_VAL_OLD                207
#define IDC_TEXT_OLD                    208
#define IDC_EDIT_HUE_DELTA              209
#define IDC_EDIT_SAT_DELTA              210
#define IDC_EDIT_VAL_DELTA              211
#define IDC_TEXT_DELTA                  212
#define IDC_STATIC_OLD                  213
#define IDC_STATIC_NEW                  214
#define IDB_UP                          215
#define IDB_DOWN                        216
#define IDC_MESSAGE_TEXT                1000
#define IDC_STATUS_ICON                 1001
#define IDC_ENABLE_SIZE                 1007
#define IDC_MAX_SHAPES_ENABLE           1008
#define IDC_WIDTH                       1009
#define IDC_HEIGHT                      1010
#define IDC_MAX_SHAPES                  1011
#define IDC_PARTIAL                     1012
#define IDC_ABOUT_ICON                  1013
#define IDC_WELCOME                     1014
#define IDC_START_WELCOME               1014
#define IDC_RANDOM                      1015
#define IDC_RANDOM_SPIN                 1016
#define IDC_STATUS_TEXT                 1017
#define IDC_EDIT_HEIGHT                 1018
#define IDC_EDIT_MINSIZE                1019
#define IDC_START_NEW                   1020
#define IDC_START_NONE                  1021
#define IDC_OPEN_RENDER                 1022
#define IDC_IMAGE_CROP                  1023
#define IDC_IMAGE_CROP2                 1024
#define IDC_RENDER_MAXIMIZE             1025
#define IDC_NODISPLAY                   1027
#define IDC_COLORPICKER                 1028
#define IDC_BORDER_SLIDER               1029
#define IDC_MOVIE_ZOOM                  1030
#define IDC_JPG_QUALITY                 1032
#define IDT_JPG_QUALITY                 1033
#define IDC_EMBED_CFDG_DEF              1034
#define IDC_MOVIE_SETTINGS              5000
#define IDC_USERNAME                    5001
#define IDC_PASSWORD                    5002
#define IDC_UPLOAD_TITLE                5003
#define IDC_UPLOAD_FILENAME             5004
#define IDC_UPLOAD_VARIATION            5005
#define IDC_ENCODE_PNG8                 5006
#define IDC_ENCODE_JPEG                 5007
#define IDC_UPLOAD_NOTE                 5008
#define IDC_UPLOAD_REGISTER             5009
#define IDC_UPLOAD_CROP                 5010
#define IDC_FDROPPER                    5011
#define IDC_EDIT1                       5012
#define IDC_UPLOAD_STATUS               5012
#define IDC_EDIT2                       5013
#define IDC_EDIT3                       5014
#define IDC_SDROPPER                    5015
#define IDC_START_COLOR                 5016
#define IDC_FINISH_COLOR                5017
#define IDC_SLIDER_RED                  5018
#define IDC_SLIDER_GREEN                5019
#define IDC_SLIDER3                     5020
#define IDC_SLIDER_BLUE                 5020
#define IDC_EDIT4                       5021
#define IDC_MULT_DELTA                  5021
#define IDC_RADIO3                      5024
#define IDC_RED                         5025
#define IDC_GREEN                       5026
#define IDC_BLUE                        5027
#define IDC_HUESAT                      5028
#define IDC_GREENS                      5032
#define IDC_BRIGHT                      5033
#define IDC_SWELL                       5034
#define IDC_FWELL                       5035
#define IDC_BRIGHT3                     5036
#define IDC_BLUES                       5036
#define IDC_REDS                        5037
#define IDC_STATIC_HSB_RECT             5038
#define IDC_BUTTON1                     5039
#define IDC_SKIP_ACCT                   5040
#define IDC_HTML_STATUS                 5041
#define IDC_SAVE_UNIT_TILE              5042
#define IDC_SAVE_RECT_TILE              5043
#define IDC_VARIATION_LABEL             5044
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_RENDERING_OPTIONS            32771
#define ID_RENDERING_RANDOMIZE          32772
#define ID_RENDER_RENDER                32773
#define ID_RENDER_STOP                  32774
#define ID_RENDER_RENDERTOSIZE          32775
#define ID_RENDER_SAVEIMAGE             32776
#define ID_FILE_REVERT                  32777
#define ID_COLORPICKER                  32778
#define ID_RENDER_RENDERTOSVG           32779
#define ID_RENDER_ANIMATE               32780
#define ID_RENDER_SAVEMOVIE             32781
#define ID_RENDER_PREFS                 32782
#define ID_EDIT_SETFONT                 32783
#define ID_RENDER_UPLOADTOGALLERY       32784
#define ID_RENDER_RENDERREPEAT          32787
#define ID_RENDER_REPEAT                32788
#define ID_RENDER_USELEGACYVARIATIONS   32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         5045
#define _APS_NEXT_SYMED_VALUE           5101
#endif
#endif
