/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125444-g6d72600a30-20260703"
#endif /* AVUTIL_FFVERSION_H */
